title: Just the Docs Implementation
description: Trting to get this template to work 
theme: just-the-docs

url: https://github.com/LaurentiusCanadensis/jubilant-enigma

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
